// tugas-fesisko/src/views/products/SingleProduct.vue
<template>
  <div v-if="product" class="pt-5">
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-5">
      <div class="rounded-lg overflow-hidden w-[80%] sm:w-auto mx-auto">
        <img :src="product.basePathImage + '/' + product.product_img" alt="" />
      </div>
      <div class="text-lg sm:text-2xl leading-loose">
        <table class="w-full table-auto">
          <tr>
            <td>Name</td>
            <td>{{ product.product_name }}</td>
          </tr>
          <tr>
            <td>Price</td>
            <td>{{ Number(product.product_price).toLocaleString("id-ID", { style: "currency", currency: "IDR" }) }}</td>
          </tr>
          <tr>
            <td>Stock</td>
            <td>{{ product.product_qty_stock }}</td>
          </tr>
          <tr>
            <td>Weight</td>
            <td>{{ product.product_weight }}gr</td>
          </tr>
          <tr>
            <td>Description</td>
            <td>{{ product.product_description ? product.product_description : "-" }}</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
  <FlexCenter v-else class="pb-16">
    <h1 class="text-3xl">Loading...</h1>
  </FlexCenter>
</template>

<script setup>
import { ref, watch } from "vue";
import { useRoute } from "vue-router";
import FlexCenter from "../../components/FlexCenter.vue";
const product = ref(null);
const route = useRoute();
const id = ref(route.params.id);
async function fetchSingleData() {
  product.value = null;
  let res = await fetch(`https://sistemtoko.com/public/demo/product/${id.value}}`);
  product.value = await res.json();
}
fetchSingleData();
watch(id, fetchSingleData);
</script>

<style setup>
table tr {
  @apply border-b;
}

table tr td {
  @apply py-3;
}
table tr td:last-child {
  @apply font-semibold capitalize;
}
</style>

// final-project-fesisko/src/pages/products/SingleProduct.jsx
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useParams } from "react-router-dom";
import { getAllProducts, getDetailProduct, getStatus } from "../../features/productsSlice";
import { imgUrl } from "../../constants/contants";
import { Prev, Spinner } from "../../components/Tags";
import { FaCartPlus } from "react-icons/fa";

const SingleProduct = () => {
  const { id } = useParams();
  const dispatch = useDispatch();
  const status = useSelector(getStatus);

  const product = useSelector(getAllProducts);

  useEffect(() => {
    dispatch(getDetailProduct(id));
  }, [dispatch, id]);

  let content = "";
  if (status === "loading") {
    content = <Spinner />;
  } else if (status === "succeeded") {
    content = (
      <>
        <Prev />
        <section className="grid grid-cols-2 gap-3 pb-5">
          <figure className="h-[calc(100vh-10rem)]">
            <img
              src={imgUrl + product.product_img}
              alt={product.product_name}
              className="rounded-lg h-full w-full object-cover"
            />
          </figure>
          <div className="p-5 bg-white rounded-lg overflow-hidden">
            <table className="w-full">
              <tbody className="text-left leading-loose">
                <tr className="border-b">
                  <th>Name</th>
                  <td className="capitalize">{product && product.product_name}</td>
                </tr>
                <tr className="border-b">
                  <th>Price</th>
                  <td>Rp{parseInt(product.product_price).toLocaleString("id-ID")}</td>
                </tr>
                <tr className="border-b">
                  <th>Stock</th>
                  <td>{product.product_qty_stock}</td>
                </tr>
                <tr className="border-b">
                  <th>Weight</th>
                  <td>{product.product_weight}</td>
                </tr>
                <tr className="border-b">
                  <th>Status</th>
                  <td>{product.product_status}</td>
                </tr>
                <tr>
                  <th></th>
                  <td className="text-end">
                    <button className="border p-3 mt-3 rounded">
                      <FaCartPlus className="text-xl" />
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>
      </>
    );
  }

  return content;
};

export default SingleProduct;
